import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        makt: {
          emerald: "#0D4734",
          "emerald-dark": "#002F20",
          "emerald-light": "#19503C",
          "emerald-surface": "#F0F5F2",
          gold: "#D4AF37",
          "gold-light": "#FED65B",
          "gold-dark": "#735C00",
          "gold-pale": "#FDF7E7",
          forest: "#06281E",
          surface: "#F8FAF8",
        },
        "primary-container": "#0d4734",
        "on-primary": "#ffffff",
        "on-primary-container": "#7fb59c",
        "primary-fixed": "#b6efd4",
        "primary-fixed-dim": "#9bd2b8",
        "on-primary-fixed": "#002115",
        "on-primary-fixed-variant": "#19503c",
        "secondary-container": "#fed65b",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#745c00",
        "secondary-fixed": "#ffe088",
        "secondary-fixed-dim": "#e9c349",
        "on-secondary-fixed": "#241a00",
        "on-secondary-fixed-variant": "#574500",
        "tertiary": "#0d2e23",
        "tertiary-container": "#244439",
        "tertiary-fixed": "#c7eada",
        "tertiary-fixed-dim": "#abcebf",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#8fb1a2",
        "on-tertiary-fixed": "#002117",
        "on-tertiary-fixed-variant": "#2d4d41",
        "surface": "#f9f9ff",
        "surface-dim": "#cfdaf2",
        "surface-bright": "#f9f9ff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f0f3ff",
        "surface-container": "#e7eeff",
        "surface-container-high": "#dee8ff",
        "surface-container-highest": "#d8e3fb",
        "on-surface": "#111c2d",
        "on-surface-variant": "#404944",
        "inverse-surface": "#263143",
        "inverse-on-surface": "#ecf1ff",
        "outline": "#707974",
        "outline-variant": "#c0c9c2",
      },
      fontFamily: {
        sans: ["var(--font-inter)", "sans-serif"],
        display: ["var(--font-plus-jakarta)", "sans-serif"],
        body: ["var(--font-inter)", "sans-serif"],
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      backgroundImage: {
        "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
        "gradient-conic":
          "conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))",
      },
    },
  },
  plugins: [],
};
export default config;
