-- ============================================================
-- Migration 11: Fix Approval Constraints & Add Helper Columns
-- ============================================================

-- 1. Drop UNIQUE constraint on pengajuan_approvals (pengajuan_id, workflow_level)
--    agar workflow bisa di-resubmit dan level yang sama bisa diapprove lagi.
--    Kita ganti dengan index biasa (non-unique).
--    (Constraint dibuat di migration 10 via: UNIQUE (pengajuan_id, workflow_level))

DO $$
BEGIN
  -- Drop constraint if exists (name auto-generated by postgres)
  IF EXISTS (
    SELECT 1 FROM pg_constraint 
    WHERE conname = 'pengajuan_approvals_pengajuan_id_workflow_level_key'
    AND conrelid = 'public.pengajuan_approvals'::regclass
  ) THEN
    ALTER TABLE public.pengajuan_approvals 
      DROP CONSTRAINT pengajuan_approvals_pengajuan_id_workflow_level_key;
  END IF;
END $$;

-- Tambah index non-unique untuk performa query
CREATE INDEX IF NOT EXISTS idx_pengajuan_approvals_pengajuan_id 
  ON public.pengajuan_approvals(pengajuan_id);

CREATE INDEX IF NOT EXISTS idx_pengajuan_approvals_level 
  ON public.pengajuan_approvals(pengajuan_id, workflow_level);

-- 2. Tambah kolom round untuk mencatat putaran approval (setelah resubmit = round baru)
ALTER TABLE public.pengajuan_approvals 
  ADD COLUMN IF NOT EXISTS approval_round INTEGER DEFAULT 1;

-- 3. Tambah kolom max_approval_level di pengajuan_peminjaman
--    (snapshot jumlah level saat pengajuan disubmit, agar bisa cek progress)
ALTER TABLE public.pengajuan_peminjaman 
  ADD COLUMN IF NOT EXISTS max_approval_level INTEGER DEFAULT NULL;

-- 4. Tambah index pada pengajuan_peminjaman untuk filter status+level
CREATE INDEX IF NOT EXISTS idx_pengajuan_status 
  ON public.pengajuan_peminjaman(status);

CREATE INDEX IF NOT EXISTS idx_pengajuan_current_level 
  ON public.pengajuan_peminjaman(current_approval_level);

-- 5. Update RLS policies agar lebih spesifik
-- (Sudah ada dari migration 10, tidak perlu tambah lagi)
